page_admin_index:
    path:     /
    defaults: { _controller: "PageBundle:PageAdmin:index" }
    methods:  GET

page_admin_show:
    path:     /{id}/show
    defaults: { _controller: "PageBundle:PageAdmin:show" }
    methods:  GET

page_admin_new:
    path:     /new
    defaults: { _controller: "PageBundle:PageAdmin:new" }
    methods:  [GET, POST]

page_admin_edit:
    path:     /{id}/edit
    defaults: { _controller: "PageBundle:PageAdmin:edit" }
    methods:  [GET, POST]

page_admin_delete:
    path:     /{id}/delete
    defaults: { _controller: "PageBundle:PageAdmin:delete" }
    methods:  DELETE
